CREATE TABLE IF NOT EXISTS bookmark_list (
    view_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title TEXT NOT NULL,
    url_link TEXT NOT NULL,
    rating INTEGER NOT NULL,
    description_text TEXT NOT NULL    
);